# Generated by Django 3.1.12 on 2024-12-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100)),
                ('file_urls', models.JSONField()),
            ],
            options={
                'db_table': 'face_users',
            },
        ),
    ]
